name: dictum-cli
on:
  schedule:
    - cron: '0 4 * * *'
  push:
    paths-ignore:
    - 'docs/**'
    - '**.md'
    branches: 
      - main
  pull_request:
    paths-ignore:
    - 'docs/**'
    - '**.md'
    branches: 
      - main

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-20.04
    steps:

      - name: Login Docker.io
        uses: docker/login-action@v1
        with:
          logout: true
          registry: docker.io
          username: ${{ secrets.ROBOT_USER_DOCKERHUB }}
          password: ${{ secrets.ROBOT_TOKEN_DOCKERHUB }}

      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Rake Variables
        run: |
          set -x ; \
          echo "varrundate=$(date +%y%m%d%I%M%S)" >> ${GITHUB_ENV};\
          echo "kubectl_version=$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)" >> ${GITHUB_ENV};\
          echo "dictum_version=$(curl -sL https://api.github.com/repos/Dictum-SM/dictum-cli/releases/latest | jq -r '.tag_name' | sed 's/v//g')" >> ${GITHUB_ENV};\
          echo;  

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Image 
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            docker.io/${{ secrets.GIT_PROJECT }}/${{ github.workflow }}
            docker.io/${{ secrets.GIT_PROJECT }}/${{ github.workflow }}:${{ env.dictum_version }}
            docker.io/${{ secrets.GIT_PROJECT }}/${{ github.workflow }}:${{ env.dictum_version }}-${{ env.varrundate }}-${{ github.sha }}
          build-args: |
            dictum_version=${{ env.dictum_version }}
            kubectl_version=${{ env.kubectl_version }}
